### ISSUE TITLE
Testes de Generalização para o template Síntese Tecnologia e Informática - Licitações

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#120]
DoD: Realizar o teste de generalização para todos os municípios cobertos pelo template Síntese Tecnologia e Informática para a tag Licitações.

**Comment by asafeclemente** [comment]
Não priorizado.

**Comment by albertoueda** [comment]
O validador de licitações foi dividido em suas respectivas subtags.
