### ISSUE TITLE
Coletor para o template Portaltp - Despesas - Pagamentos

### ISSUE THREAD

**Issue by isabel-elise** [MPMG-DCC-UFMG/F01#1954]

**Comment by albertoueda** [comment]
@isabel-elise favor confirmar label do template (Portal Facil (60) ) e outras possíveis diferenças em labels.

**Comment by isabel-elise** [comment]
> @isabel-elise favor confirmar label do template (Portal Facil (60) ) e outras possíveis diferenças em labels.

Corrigido!
