### ISSUE TITLE
Testar validadores da tag licitações para Ipatinga

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#44]
DoD:  Testar os validadores para cada um dos itens nos dados de ipatinga

- [x] Número/Ano do Edital

- [x] Modalidade

- [x] Objeto

- [x] Situação/Status

- [x] Divulgação do resultado da licitação

- [x] Registro dos procedimentos de inexigibilidade

- [x] Registros de procedimentos de dispensa de licitação

- [x] Disponibiliza o conteúdo integral dos editais

- [ ] Possibilita a consulta aos resultados das licitações ocorridas

**Comment by asafeclemente** [comment]
Não priorizado
