### ISSUE TITLE
Teste de generalização dos validadores da tag acesso à informação

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#63]
- [x] Divinópolis
- [x]  Pará de Minas 
- [x]  Uberaba 
- [x]  Uberlândia 
- [x]  Montes Claros 
- [x]  Teófilo Otoni 
- [ ]  Varginha 
- [ ]  Passos 
- [x]  Pouso Alegre 
- [ ]  Juiz de Fora 
- [x] Ipatinga | Betim 
- [x]  Congonhas 
- [x]  Paracatu

**Comment by asafeclemente** [comment]
Não priorizado.
