### ISSUE TITLE
Coleta do dados da Tag de despesas (Empenhos e Pagamentos)

### ISSUE THREAD

**Issue by CinthiaS** [MPMG-DCC-UFMG/F01#64]
DoD: Coleta dos dados dos de municípios

Divinópolis
Pará de Minas
Uberaba
Uberlândia
Montes Claros
Teófilo Otoni
Varginha
Passos
Pouso Alegre
Juiz de Fora
Governador Valadares
Ipatinga
Betim
Congonhas
Paracatu

**Comment by albertoueda** [comment]
Não priorizado.
