### ISSUE TITLE
Treinamento de Novos Membros

### ISSUE THREAD

**Issue by albertoueda** [MPMG-DCC-UFMG/F01#903]
|  | Acesso Discord MP? | Acesso servidor MP? | Time F01 GitHub? | Leu PDF Treinamento F01? | YouTube Coletor C01? |  Completou Tutorial (Wiki C01)? | Viu demonstração (Isabel)? | Coleta Local OK? | Coleta MP OK? |
| - | - | - | - | - | - | - | - | - | - |
| Mara | ✔️ |  ✔️ | ✔️  | ✔️ | ✔️ |✔️   | ✔️ |✔️  |  ✔️ | 
| Antônio | ✔️ | ✔️  | ✔️ | ✔️  |✔️  | ✔️ | ✔️ | ✔️ |  ✔️|
| Gabi | ✔️  |    |  ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  |  |
| Rafael | ✔️  |  ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |  ✔️| 
| Jorge | ✔️ |  ✔️  | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | ✔️| ✔️ | 
 
\* Solicitado ao Zilton

ℹ️ Para mais informações sobre o treinamento, favor utilizar nosso canal da F01 no Discord.

**Comment by jorgesilva2407** [comment]
Estou terminando o tutorial da wiki C01 neste momento

**Comment by jorgesilva2407** [comment]
Completei o tutorial da wiki

**Comment by rafaelmg7** [comment]
Já completei o tutorial, tenho acesso ao servidor do MP e minhas coletas locais estão OK.

**Comment by dalila20** [comment]
consegui acessar o servidor do MP!

**Comment by albertoueda** [comment]
Treinamento concluído. Lembrar de utilizar esse template para possíveis próximos treinamentos. 

Parabéns @dalila20 @jorgesilva2407 @AntonioNvs @rafaelmg7 !!! 🎓 

Congratulações para a ótima líder @isabel-elise ! 👏🏼
